apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: proy-final-cafs
data:
  MY_DATABASE_DRIVER: "mysql"
  DB_HOST: "mysql"
  DB_USER_NAME: "root"
  DB_NAME: "mydb"
  DB_PORT: "3306"